version: '3.8'

services:
  elasticsearch:
    container_name: elasticsearch
    build: elasticsearch
    networks:
      - elk
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/etc/elesticsearch/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9200
      - 9300
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    restart: always
  kibana:
    container_name: kibana
    build: kibana
    networks:
      - elk
    ports:
      - 5601:5601
  logstash:
    container_name: logstash
    build: logstash
    networks:
      - elk
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/config/:/usr/share/logstash/config/
      - ./data/app-logs/:/tmp/app-logs/
    ports:
      - 5044:5044
      - 9600:9600
    restart: always

volumes:
  elasticsearch-data:
    driver: local

networks:
  elk:
    driver: bridge
